FROM golang:1.17-alpine as builder

# Installing nodejs
RUN apk add --no-cache --update nodejs npm curl bash build-base

# Installing Yarn
RUN curl -o- -L https://yarnpkg.com/install.sh | bash
ENV PATH="$PATH:/root/.yarn/bin:/root/.config/yarn/global/node_modules"

WORKDIR /ox
ADD . .

# Building the application binary in bin/app 
RUN go build -v ./cmd/ox 

# Running unit tests
RUN go test --tags sqlite -v --cover ./...

# Running integration tests
RUN go test --tags integration -v --cover ./cli/...
